# Generated by Django 5.1.7 on 2025-03-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participatnts',
            new_name='participants',
        ),
    ]
